version: '3'
services:
  node:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    networks:
      - internal
      - proxy
    volumes:
      - ./:/app

networks:
  internal:
  proxy:
    name: scaling
    external: true
